# Pinhole Camera Model Practice Questions

## Question 1: Perspective Projection

A 3D point in the camera coordinate system is given by `p_c = [10, 5, 20]`. 
The camera has a focal length `f` of 50mm. 
Calculate the position of the projection of this point on the image plane in meters.

In [2]:
# Your code here
p_c = [10, 5, 20]
X, Y, Z = p_c
f = 50/1000

x = f * X / Z
y = f * Y / Z

print(f"({x}, {y})")

(0.025, 0.0125)


---

## Question 2: Conversion to Pixels

Given the projected point from Question 1, convert its coordinates from meters to pixels. 
Assume the following intrinsic parameters: 
- `s_x` = 800 pixels/meter
- `s_y` = 800 pixels/meter
- `o_x` = 320 pixels
- `o_y` = 240 pixels
What are the pixel coordinates `(u^I, v^I)`?


In [3]:
# Your code here

s_x = 800
s_y = 800
o_x = 320
o_y = 240

u = s_x * x + o_x
v = s_y * y + o_y

print(f"({u}, {v})")

(340.0, 250.0)


---

## Question 3: Intrinsic Matrix

Construct the intrinsic calibration matrix `K` using the parameters from Question 2, assuming no skew (`s_θ = 0`).

In [6]:
# Your code here
K = [[s_x, 0, o_x], [0, s_y, o_y], [0, 0, 1]]

for i in K:
    print(", ".join(str(j) for j in i))

800, 0, 320
0, 800, 240
0, 0, 1


---

## Question 4: Point Projection with Known Pose

A point in the world frame is given by `p_w = [2, 3, 50]`. The camera's pose `T_w^c` is given by an identity rotation matrix and a translation vector `t_w^c = [0, 0, 10]`. [cite_start]Using the intrinsic matrix `K` from Question 3, calculate the pixel coordinates of the projected point. [cite: 14, 16, 17]

In [7]:
# Your code here
R_w = [2, 3, 60]

X = 2
Y = 3
Z = 60

x = X / Z
y = Y / Z

u = s_x * x + o_x
v = s_y * y + o_y

print(f"({u}, {v})")

(346.6666666666667, 280.0)


---

## Question 5: Radial Distortion

A point is projected on the image plane at `(u_distort^I, v_distort^I) = (400, 350)` including radial distortion. Given distortion coefficients `a1 = 0.0001` and `a2 = 0.0000002` and the principal point `(o_x, o_y) = (320, 240)`, calculate the corrected pixel coordinates `(u^I, v^I)`.

In [8]:
# Your code here

o_x = 320
o_y = 240

a1 = 0.0001
a2 = 0.0000002
ud = 400
vd = 350

r2 = (ud - o_x) ** 2 + (vd - o_y) ** 2

u1 = (1 + a1 * r2 + a2 * (r2 ** 2)) * (ud - o_x) + o_x
v1 = (1 + a1 * r2 + a2 * (r2 ** 2)) * (vd - o_y) + o_y

print(f"({u1}, {v1})")

(6024.0, 8083.0)
